// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using test3.DAL.test3.Models;

namespace test3.DAL.test3.Context;

public partial class test3Context : DbContext
{
    public test3Context(DbContextOptions<test3Context> options)
        : base(options)
    {
    }

    public virtual DbSet<Author> Authors { get; set; }

    public virtual DbSet<Book> Books { get; set; }

    public virtual DbSet<BookStatus> BookStatuses { get; set; }

    public virtual DbSet<Borrow> Borrows { get; set; }

    public virtual DbSet<BorrowStatus> BorrowStatuses { get; set; }

    public virtual DbSet<Client> Clients { get; set; }

    public virtual DbSet<Collection> Collections { get; set; }

    public virtual DbSet<Favorite> Favorites { get; set; }

    public virtual DbSet<History> Histories { get; set; }

    public virtual DbSet<Language> Languages { get; set; }

    public virtual DbSet<Notification> Notifications { get; set; }

    public virtual DbSet<Reservation> Reservations { get; set; }

    public virtual DbSet<ReservationStatus> ReservationStatuses { get; set; }

    public virtual DbSet<SystemTime> SystemTimes { get; set; }

    public virtual DbSet<Models.Type> Types { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Author>(entity =>
        {
            entity.HasKey(e => e.AuthorId).HasName("PK_Author_AuthorId");

            entity.ToTable("Author");

            entity.HasIndex(e => e.Author1, "UK_Author_Author").IsUnique();

            entity.Property(e => e.AuthorId).ValueGeneratedOnAdd();
            entity.Property(e => e.Author1)
                .HasMaxLength(50)
                .HasColumnName("Author");
        });

        modelBuilder.Entity<Book>(entity =>
        {
            entity.HasKey(e => e.BookId).HasName("PK_Book_BookId");

            entity.ToTable("Book");

            entity.HasIndex(e => e.CollectionId, "IX_Book_CollectionId");

            entity.HasIndex(e => e.BookCode, "UK_Book_BookCode").IsUnique();

            entity.Property(e => e.BookCode)
                .HasMaxLength(23)
                .IsUnicode(false);

            entity.HasOne(d => d.BookStatus).WithMany(p => p.Books)
                .HasForeignKey(d => d.BookStatusId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Book_BookStatusId");

            entity.HasOne(d => d.Collection).WithMany(p => p.Books)
                .HasForeignKey(d => d.CollectionId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Book_CollectionId");
        });

        modelBuilder.Entity<BookStatus>(entity =>
        {
            entity.HasKey(e => e.BookStatusId).HasName("PK_BookStatus_BookStatusId");

            entity.ToTable("BookStatus");

            entity.HasIndex(e => e.BookStatus1, "UK_BookStatus_BookStatus").IsUnique();

            entity.Property(e => e.BookStatusId).ValueGeneratedOnAdd();
            entity.Property(e => e.BookStatus1)
                .HasMaxLength(50)
                .HasColumnName("BookStatus");
        });

        modelBuilder.Entity<Borrow>(entity =>
        {
            entity.HasKey(e => e.BorrowId).HasName("PK_Borrow_BorrowId");

            entity.ToTable("Borrow");

            entity.HasIndex(e => e.BookId, "IX_Borrow_BookId");

            entity.HasIndex(e => e.Cid, "IX_Borrow_CId");

            entity.Property(e => e.Cid).HasColumnName("CId");

            entity.HasOne(d => d.Book).WithMany(p => p.Borrows)
                .HasForeignKey(d => d.BookId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Borrow_BookId");

            entity.HasOne(d => d.BorrowStatus).WithMany(p => p.Borrows)
                .HasForeignKey(d => d.BorrowStatusId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Borrow_BorrowStatusId");

            entity.HasOne(d => d.CidNavigation).WithMany(p => p.Borrows)
                .HasForeignKey(d => d.Cid)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Borrow_CId");

            entity.HasOne(d => d.Reservation).WithMany(p => p.Borrows)
                .HasForeignKey(d => d.ReservationId)
                .HasConstraintName("FK_Borrow_ReservationId");
        });

        modelBuilder.Entity<BorrowStatus>(entity =>
        {
            entity.HasKey(e => e.BorrowStatusId).HasName("PK_BorrowStatus_BorrowStatusId");

            entity.ToTable("BorrowStatus");

            entity.HasIndex(e => e.BorrowStatus1, "UK_BorrowStatus_BorrowStatus").IsUnique();

            entity.Property(e => e.BorrowStatusId).ValueGeneratedOnAdd();
            entity.Property(e => e.BorrowStatus1)
                .HasMaxLength(50)
                .HasColumnName("BorrowStatus");
        });

        modelBuilder.Entity<Client>(entity =>
        {
            entity.HasKey(e => e.Cid).HasName("PK_Client_CId");

            entity.ToTable("Client");

            entity.HasIndex(e => e.Cacc, "UK_Client_CAcc").IsUnique();

            entity.HasIndex(e => e.Cphone, "UK_Client_CPhone").IsUnique();

            entity.HasIndex(e => e.Guid, "UK_Client_Guid").IsUnique();

            entity.Property(e => e.Cid).HasColumnName("CId");
            entity.Property(e => e.Cacc)
                .HasMaxLength(255)
                .IsUnicode(false)
                .HasColumnName("CAcc");
            entity.Property(e => e.Cname)
                .HasMaxLength(50)
                .HasColumnName("CName");
            entity.Property(e => e.Cphone)
                .HasMaxLength(20)
                .IsUnicode(false)
                .HasColumnName("CPhone");
            entity.Property(e => e.Cpwd)
                .HasMaxLength(128)
                .IsUnicode(false)
                .HasColumnName("CPwd");
            entity.Property(e => e.Fid)
                .HasMaxLength(100)
                .IsUnicode(false)
                .HasColumnName("FId");
            entity.Property(e => e.Gid)
                .HasMaxLength(100)
                .IsUnicode(false)
                .HasColumnName("GId");
            entity.Property(e => e.Guid).HasDefaultValueSql("(newid())");
        });

        modelBuilder.Entity<Collection>(entity =>
        {
            entity.HasKey(e => e.CollectionId).HasName("PK_Collection_CollectionId");

            entity.ToTable("Collection");

            entity.HasIndex(e => e.LanguageId, "IX_Collection_LanguageId");

            entity.HasIndex(e => e.Publisher, "IX_Collection_Publisher");

            entity.HasIndex(e => e.Title, "IX_Collection_Title");

            entity.HasIndex(e => e.TypeId, "IX_Collection_TypeId");

            entity.HasIndex(e => e.Isbn, "UK_Collection_ISBN").IsUnique();

            entity.Property(e => e.Isbn)
                .HasMaxLength(17)
                .IsUnicode(false)
                .HasColumnName("ISBN");
            entity.Property(e => e.Publisher).HasMaxLength(50);
            entity.Property(e => e.Title).HasMaxLength(100);
            entity.Property(e => e.Translator).HasMaxLength(50);

            entity.HasOne(d => d.Language).WithMany(p => p.Collections)
                .HasForeignKey(d => d.LanguageId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Collection_LanguageId");

            entity.HasOne(d => d.Type).WithMany(p => p.Collections)
                .HasForeignKey(d => d.TypeId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Collection_TypeId");

            entity.HasMany(d => d.Authors).WithMany(p => p.Collections)
                .UsingEntity<Dictionary<String, object>>(
                    "MapCa",
                    r => r.HasOne<Author>().WithMany()
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.ClientSetNull)
                        .HasConstraintName("FK_MapCA_AuthorId"),
                    l => l.HasOne<Collection>().WithMany()
                        .HasForeignKey("CollectionId")
                        .OnDelete(DeleteBehavior.ClientSetNull)
                        .HasConstraintName("FK_MapCA_CollectionId"),
                    j =>
                    {
                        j.HasKey("CollectionId", "AuthorId").HasName("CPK_MapCA");
                        j.ToTable("MapCA");
                        j.HasIndex(new[] { "AuthorId" }, "IX_MapCA_AuthorId");
                    });
        });

        modelBuilder.Entity<Favorite>(entity =>
        {
            entity.HasKey(e => e.FavoriteId).HasName("PK_Favorite_FavoriteId");

            entity.ToTable("Favorite");

            entity.HasIndex(e => new { e.Cid, e.CollectionId }, "CUK_Favorite").IsUnique();

            entity.Property(e => e.Cid).HasColumnName("CId");

            entity.HasOne(d => d.CidNavigation).WithMany(p => p.Favorites)
                .HasForeignKey(d => d.Cid)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Favorite_CId");

            entity.HasOne(d => d.Collection).WithMany(p => p.Favorites)
                .HasForeignKey(d => d.CollectionId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Favorite_CollectionId");
        });

        modelBuilder.Entity<History>(entity =>
        {
            entity.HasKey(e => e.HistoryId).HasName("PK_History_HistoryId");

            entity.ToTable("History");

            entity.HasIndex(e => e.BorrowId, "IX_History_BorrowId");

            entity.HasOne(d => d.Borrow).WithMany(p => p.Histories)
                .HasForeignKey(d => d.BorrowId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_History_BorrowId");
        });

        modelBuilder.Entity<Language>(entity =>
        {
            entity.HasKey(e => e.LanguageId).HasName("PK_Language_LanguageId");

            entity.ToTable("Language");

            entity.HasIndex(e => e.Language1, "UK_Language_Language").IsUnique();

            entity.Property(e => e.LanguageId).ValueGeneratedOnAdd();
            entity.Property(e => e.Language1)
                .HasMaxLength(50)
                .HasColumnName("Language");
        });

        modelBuilder.Entity<Notification>(entity =>
        {
            entity.HasKey(e => e.NotificationId).HasName("PK_Notification_NotificationId");

            entity.ToTable("Notification");

            entity.Property(e => e.Cid).HasColumnName("CId");

            entity.HasOne(d => d.CidNavigation).WithMany(p => p.Notifications)
                .HasForeignKey(d => d.Cid)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Notification_CId");
        });

        modelBuilder.Entity<Reservation>(entity =>
        {
            entity.HasKey(e => e.ReservationId).HasName("PK_Reservation_ReservationId");

            entity.ToTable("Reservation");

            entity.HasIndex(e => e.Cid, "IX_Reservation_CId");

            entity.HasIndex(e => e.CollectionId, "IX_Reservation_CollectionId");

            entity.Property(e => e.Cid).HasColumnName("CId");

            entity.HasOne(d => d.Book).WithMany(p => p.Reservations)
                .HasForeignKey(d => d.BookId)
                .HasConstraintName("FK_Reservation_BookId");

            entity.HasOne(d => d.CidNavigation).WithMany(p => p.Reservations)
                .HasForeignKey(d => d.Cid)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Reservation_CId");

            entity.HasOne(d => d.Collection).WithMany(p => p.Reservations)
                .HasForeignKey(d => d.CollectionId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Reservation_CollectionId");

            entity.HasOne(d => d.ReservationStatus).WithMany(p => p.Reservations)
                .HasForeignKey(d => d.ReservationStatusId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Reservation_ReservationStatusId");
        });

        modelBuilder.Entity<ReservationStatus>(entity =>
        {
            entity.HasKey(e => e.ReservationStatusId).HasName("PK_ReservationStatus_ReservationStatusId");

            entity.ToTable("ReservationStatus");

            entity.HasIndex(e => e.ReservationStatus1, "UK_ReservationStatus_ReservationStatus").IsUnique();

            entity.Property(e => e.ReservationStatusId).ValueGeneratedOnAdd();
            entity.Property(e => e.ReservationStatus1)
                .HasMaxLength(50)
                .HasColumnName("ReservationStatus");
        });

        modelBuilder.Entity<SystemTime>(entity =>
        {
            entity.HasKey(e => e.Oid).HasName("PK_SystemTime_OId");

            entity.ToTable("SystemTime");

            entity.Property(e => e.Oid).HasColumnName("OId");
            entity.Property(e => e.Cdate)
                .HasDefaultValueSql("(CONVERT([date],getdate()))")
                .HasColumnName("CDate");
        });

        modelBuilder.Entity<Models.Type>(entity =>
        {
            entity.HasKey(e => e.TypeId).HasName("PK_Type_TypeId");

            entity.ToTable("Type");

            entity.HasIndex(e => e.Type1, "UK_Type_Type").IsUnique();

            entity.Property(e => e.TypeId).ValueGeneratedOnAdd();
            entity.Property(e => e.Type1)
                .HasMaxLength(50)
                .HasColumnName("Type");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}
