// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace test3.DAL.test3.Models;

public partial class Author
{
    public Byte AuthorId { get; set; }

    public String Author1 { get; set; } = null!;

    public String? Desc { get; set; }

    public virtual ICollection<Collection> Collections { get; set; } = new List<Collection>();
}