// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace test3.DAL.test3.Models;

public partial class BookStatus
{
    public byte BookStatusId { get; set; }

    public string BookStatus1 { get; set; } = null!;

    public virtual ICollection<Book> Books { get; set; } = new List<Book>();
}