// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace test3.DAL.test3.Models;

public partial class Book
{
    public int BookId { get; set; }

    public int CollectionId { get; set; }

    public string BookCode { get; set; } = null!;

    public byte BookStatusId { get; set; }

    public DateTime AccessDate { get; set; }

    public virtual BookStatus BookStatus { get; set; } = null!;

    public virtual ICollection<Borrow> Borrows { get; set; } = new List<Borrow>();

    public virtual Collection Collection { get; set; } = null!;

    public virtual ICollection<Reservation> Reservations { get; set; } = new List<Reservation>();
}