// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace test3.DAL.test3.Models;

public partial class Borrow
{
    public Int32 BorrowId { get; set; }

    public Int32 Cid { get; set; }

    public Int32? ReservationId { get; set; }

    public Int32 BookId { get; set; }

    public DateTime BorrowDate { get; set; }

    public DateTime DueDateB { get; set; }

    public DateTime? ReturnDate { get; set; }

    public Byte BorrowStatusId { get; set; }

    public virtual Book Book { get; set; } = null!;

    public virtual BorrowStatus BorrowStatus { get; set; } = null!;

    public virtual Client CidNavigation { get; set; } = null!;

    public virtual ICollection<History> Histories { get; set; } = new List<History>();

    public virtual Reservation? Reservation { get; set; }
}