// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace test3.DAL.test3.Models;

public partial class Client
{
    public Int32 Cid { get; set; }

    public Guid Guid { get; set; }

    public String Cname { get; set; } = null!;

    public String Cacc { get; set; } = null!;

    public String Cpwd { get; set; } = null!;

    public String? Cphone { get; set; }

    public String? Fid { get; set; }

    public String? Gid { get; set; }

    public Byte Permission { get; set; }

    public virtual ICollection<Borrow> Borrows { get; set; } = new List<Borrow>();

    public virtual ICollection<Favorite> Favorites { get; set; } = new List<Favorite>();

    public virtual ICollection<Notification> Notifications { get; set; } = new List<Notification>();

    public virtual ICollection<Reservation> Reservations { get; set; } = new List<Reservation>();
}