// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace test3.DAL.test3.Models;

public partial class Client
{
    public int Cid { get; set; }

    public Guid Guid { get; set; }

    public string Cname { get; set; } = null!;

    public string Cacc { get; set; } = null!;

    public string Cpwd { get; set; } = null!;

    public string? Cphone { get; set; }

    public string? Fid { get; set; }

    public string? Gid { get; set; }

    public byte Permission { get; set; }

    public virtual ICollection<Borrow> Borrows { get; set; } = new List<Borrow>();

    public virtual ICollection<Favorite> Favorites { get; set; } = new List<Favorite>();

    public virtual ICollection<Notification> Notifications { get; set; } = new List<Notification>();

    public virtual ICollection<Reservation> Reservations { get; set; } = new List<Reservation>();
}