// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace test3.DAL.test3.Models;

public partial class Collection
{
    public Int32 CollectionId { get; set; }

    public String Title { get; set; } = null!;

    public String? Desc { get; set; }

    public Byte[]? Image { get; set; }

    public Byte TypeId { get; set; }

    public String? Translator { get; set; }

    public String Publisher { get; set; } = null!;

    public Byte LanguageId { get; set; }

    public String Isbn { get; set; } = null!;

    public DateTime PublishDate { get; set; }

    public virtual ICollection<Book> Books { get; set; } = new List<Book>();

    public virtual ICollection<Favorite> Favorites { get; set; } = new List<Favorite>();

    public virtual Language Language { get; set; } = null!;

    public virtual ICollection<Reservation> Reservations { get; set; } = new List<Reservation>();

    public virtual Type Type { get; set; } = null!;

    public virtual ICollection<Author> Authors { get; set; } = new List<Author>();
}