// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace test3.DAL.test3.Models;

public partial class Collection
{
    public int CollectionId { get; set; }

    public string Title { get; set; } = null!;

    public string? Desc { get; set; }

    public byte[]? Image { get; set; }

    public byte TypeId { get; set; }

    public string? Translator { get; set; }

    public string Publisher { get; set; } = null!;

    public byte LanguageId { get; set; }

    public string Isbn { get; set; } = null!;

    public byte? SeriesId { get; set; }

    public DateTime PublishDate { get; set; }

    public virtual ICollection<Book> Books { get; set; } = new List<Book>();

    public virtual ICollection<Favorite> Favorites { get; set; } = new List<Favorite>();

    public virtual Language Language { get; set; } = null!;

    public virtual ICollection<Reservation> Reservations { get; set; } = new List<Reservation>();

    public virtual Series? Series { get; set; }

    public virtual Type Type { get; set; } = null!;

    public virtual ICollection<Author> Authors { get; set; } = new List<Author>();
}