// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace test3.DAL.test3.Models;

public partial class Favorite
{
    public int FavoriteId { get; set; }

    public int Cid { get; set; }

    public int CollectionId { get; set; }

    public virtual Client CidNavigation { get; set; } = null!;

    public virtual Collection Collection { get; set; } = null!;
}