// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace test3.DAL.test3.Models;

public partial class Favorite
{
    public Int32 FavoriteId { get; set; }

    public Int32 Cid { get; set; }

    public Int32 CollectionId { get; set; }

    public virtual Client CidNavigation { get; set; } = null!;

    public virtual Collection Collection { get; set; } = null!;
}