// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace test3.DAL.test3.Models;

public partial class History
{
    public Int32 HistoryId { get; set; }

    public Int32 BorrowId { get; set; }

    public Byte? Score { get; set; }

    public String? Feedback { get; set; }

    public virtual Borrow Borrow { get; set; } = null!;
}