// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace test3.DAL.test3.Models;

public partial class History
{
    public int HistoryId { get; set; }

    public int BorrowId { get; set; }

    public byte? Score { get; set; }

    public string? Feedback { get; set; }

    public virtual Borrow Borrow { get; set; } = null!;
}