// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace test3.DAL.test3.Models;

public partial class Notification
{
    public Int32 NotificationId { get; set; }

    public Int32 Cid { get; set; }

    public String Message { get; set; } = null!;

    public DateTime NotificationDate { get; set; }

    public virtual Client CidNavigation { get; set; } = null!;
}