// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace test3.DAL.test3.Models;

public partial class Reservation
{
    public Int32 ReservationId { get; set; }

    public Int32 Cid { get; set; }

    public Int32 CollectionId { get; set; }

    public Int32? BookId { get; set; }

    public DateTime ReservateDate { get; set; }

    public DateTime? DueDateR { get; set; }

    public Byte ReservationStatusId { get; set; }

    public virtual Book? Book { get; set; }

    public virtual ICollection<Borrow> Borrows { get; set; } = new List<Borrow>();

    public virtual Client CidNavigation { get; set; } = null!;

    public virtual Collection Collection { get; set; } = null!;

    public virtual ReservationStatus ReservationStatus { get; set; } = null!;
}