// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace test3.DAL.test3.Models;

public partial class SystemTime
{
    public int Oid { get; set; }

    public DateTime Cdate { get; set; }
}